name: Auto Delete Subscription
on:
  schedule:
    # 23:00 по Москве (20:00 UTC) 5 апреля
    - cron: '0 20 5 4 *' 
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  clear-sub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear sub.txt
        run: |
          echo "# Срок действия подписки истек." > sub.txt
          echo "# Обратитесь к администратору для продления." >> sub.txt

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sub.txt
          git commit -m "Subscription expired"
          git push
